// This file is auto-generated by running: npm run db:types
// After starting Supabase locally, run: supabase gen types typescript --local > src/types/supabase.ts
// For now this is a placeholder so TypeScript doesn't complain

export type Database = {
  public: {
    Tables: {
      profiles: { Row: any; Insert: any; Update: any }
      doctors: { Row: any; Insert: any; Update: any }
      patients: { Row: any; Insert: any; Update: any }
      patient_status_history: { Row: any; Insert: any; Update: any }
      visits: { Row: any; Insert: any; Update: any }
      visit_notes: { Row: any; Insert: any; Update: any }
      review_actions: { Row: any; Insert: any; Update: any }
      exercises: { Row: any; Insert: any; Update: any }
      programs: { Row: any; Insert: any; Update: any }
      apta_diagnoses: { Row: any; Insert: any; Update: any }
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}
